// Waveform timeline types

/**
 * Cue point on a track's timeline.
 * Used for marking structural sections (intro, drop, breakdown, outro)
 * and as trim boundaries for export.
 */
export interface CuePoint {
  id: string                    // nanoid
  timestamp: number             // seconds from track start
  label: string                 // user-provided name
  type: 'marker' | 'trim-start' | 'trim-end'
}

/**
 * Extracted waveform peak data for canvas rendering.
 * Generated by WaveformExtractor via FFmpeg, cached to disk.
 */
export interface WaveformData {
  songId: string
  peaks: number[]               // normalized 0–1, ~2000 points
  duration: number              // seconds
  sampleRate: number            // source sample rate
  fileHash: string              // "${size}-${mtimeMs}" for cache invalidation
}

/**
 * BPM detection result.
 * Generated by BpmDetector via onset detection + autocorrelation, cached to disk.
 */
export interface BpmData {
  songId: string
  bpm: number
  firstBeatOffset: number       // seconds to first downbeat
  confidence: number            // 0–1
  fileHash: string
}

// --- IPC request types ---

export interface WaveformGenerateRequest {
  songId: string
  filePath: string
}

export interface WaveformBatchRequest {
  projectId: string
}

export interface BpmDetectRequest {
  songId: string
  filePath: string
}

export interface BpmBatchRequest {
  projectId: string
}

// --- IPC progress event types ---

export interface WaveformProgressEvent {
  songId: string
  index: number
  total: number
}

export interface BpmProgressEvent {
  songId: string
  index: number
  total: number
}
